module.exports = {
  resolve: {
    fallback: {
      crypto:     false,
      stream:     false,
      buffer:     false,
      path:       false,
      os:         false,
      fs:         false,
      net:        false,
      tls:        false,
      http:       false,
      https:      false,
      http2:      false,
      zlib:       false,
      url:        false,
      util:       false,
      assert:     false,
      tty:        false,
      readline:   false,
      constants:  false,
      events:     false,
      process:    false,
      querystring: false,
      child_process: false,
      electron:   false,
    },
  },
};
