/**
 * ImportHandler.gs
 * Google Apps Script handler for bulk-importing seed data
 * generated by tools/data-import/index.js.
 *
 * Endpoint: POST /exec?action=import
 * Body: { sheet: 'CATEGORIES'|'WALLETS'|'TRANSACTIONS'|'CONCEPTS', headers: [...], rows: [[...], ...] }
 *
 * This handler is ONLY for the initial data seed. Once the app is live,
 * all writes go through TransactionsHandler.gs, BudgetHandler.gs, etc.
 *
 * Usage from the import tool (once OAuth2 is configured):
 *   node tools/data-import/index.js --upload
 */

const ALLOWED_SHEETS = ['CATEGORIES', 'WALLETS', 'TRANSACTIONS', 'CONCEPTS'];

/**
 * Routes POST requests for the import action.
 * Called by the Apps Script doPost router in Code.gs.
 * @param {Object} payload Parsed JSON body { sheet, headers, rows }
 * @returns {Object} { success, inserted, sheet }
 */
function handleImport(payload) {
  const { sheet, headers, rows } = payload;

  if (!ALLOWED_SHEETS.includes(sheet)) {
    throw new Error(`Sheet '${sheet}' is not allowed for import. Allowed: ${ALLOWED_SHEETS.join(', ')}`);
  }

  if (!Array.isArray(headers) || !Array.isArray(rows)) {
    throw new Error('Payload must include headers (array) and rows (array of arrays).');
  }

  const ss        = SpreadsheetApp.getActiveSpreadsheet();
  const sheetObj  = ss.getSheetByName(sheet);

  if (!sheetObj) {
    throw new Error(`Sheet '${sheet}' not found in the spreadsheet.`);
  }

  // Clear existing data (preserves formatting), then write headers + rows
  sheetObj.clearContents();

  const allData = [headers, ...rows];
  sheetObj
    .getRange(1, 1, allData.length, allData[0].length)
    .setValues(allData);

  // Freeze header row
  sheetObj.setFrozenRows(1);

  return {
    success:  true,
    inserted: rows.length,
    sheet,
  };
}
